
function [LinearizedIBL, LinearizedDisturbedBD, LinearizedEF, E] =  ...
    TFMRoutineWithBayesEstimation(...
        divisionNumber, beadNumber, w, h, forceScale, ...
        cellID, forceID, A, B, thr, noiseRadius, randomState)

[X, Y, SFx, SFy, IBLx, IBLy, ~, ...
 ~, ~, ~, dBDx, dBDy, tfmc] = ... 
    generateSyntheticData(divisionNumber, ...
        beadNumber, w, h, forceScale, ...
        cellID, forceID, noiseRadius, randomState);

LinearizedIBL = reshape([reshape(IBLx, 1, []); reshape(IBLy, 1, [])], 1, []);    
LinearizedDisturbedBD = reshape([reshape(dBDx, 1, []); reshape(dBDy, 1, [])], 1, []);

gm = beadDensityMap(X, Y, beadNumber, IBLx, IBLy, divisionNumber, cellID);

[BEFx, BEFy, ~] = ...
    TFMWithBayesianEstimation(divisionNumber, tfmc.G, dBDx, dBDy, cellID, ...
        forceScale, A, B, gm, thr, X, Y, tfmc.IBLx, tfmc.IBLy);

LinearizedEF = reshape([reshape(BEFx, 1, []); reshape(BEFy, 1, [])], 1, []);
E = mean((SFx - BEFx) .^ 2 + (SFy - BEFy) .^ 2, 'all') * 2;

end
