
function [LinearizedIBL, LinearizedDisturbedBD, LinearizedEF, E] =  ...
    TFMRoutineWithRidgeRegression(...
        divisionNumber, beadNumber, w, h, forceScale, ...
        cellID, forceID, noiseRadius, randomState)

[X, Y, SFx, SFy, IBLx, IBLy, ~, ...
 ~, ~, ~, dBDx, dBDy, tfmc] = ... 
    generateSyntheticData(divisionNumber, ...
        beadNumber, w, h, forceScale, ...
        cellID, forceID, noiseRadius, randomState);

LinearizedIBL = reshape([reshape(IBLx, 1, []); reshape(IBLy, 1, [])], 1, []);    
LinearizedDisturbedBD = reshape([reshape(dBDx, 1, []); reshape(dBDy, 1, [])], 1, []);

gm = beadDensityMap(X, Y, beadNumber, IBLx, IBLy, divisionNumber, cellID);

[EFx, EFy, ~] = TFMWithRidge(divisionNumber, tfmc.G, dBDx, dBDy);

LinearizedEF = reshape([reshape(EFx, 1, []); reshape(EFy, 1, [])], 1, []);
E = mean((SFx - EFx) .^ 2 + (SFy - EFy) .^ 2, 'all') * 2;

end
